JUP-69: Add Request Lib
DeversiFi/dvf-utils pull request #41
Opened 2021-11-05 12:26 UTC by sjpbeale

Adds request util to use for http requests using [axios](https://www.npmjs.com/package/axios) as underlying lib.

* Promise based requests to replace deprecated [request-promise](https://www.npmjs.com/package/request-promise) lib
* Exposes get / post only currently but can allow options, head, put, delete, etc if needed
* Limits valid request options to avoid exposing underlying lib options.  Less tracking down where it's used for future library replacements
* Json response by default (majority of use cases) but allows response type switching
* Exposes custom errors separately for external confirmation as per [bridgeWithdrawal](https://github.com/DeversiFi/launch-deversifi/blob/dev/dvf-stark-trading/src/lib/exchange/bridgedWithdrawal/watchAndExecuteOnChain.js#L36) / [fastWithdrawal](https://github.com/DeversiFi/launch-deversifi/blob/dev/dvf-stark-trading/src/lib/exchange/fastWithdrawal/watchAndExecuteOnChain.js#L38) implimentations
* Note: does not support targeted catch blocks used in [pub-api request](https://github.com/DeversiFi/launch-deversifi/blob/dev/dvf-pub-api/src/lib/services/request.js#L14-L20), this was bluebird promise logic which is unnecessary overhead

2021-11-05 12:28 UTC, Matko95 approved these changes

2021-11-05 17:26 UTC, adrian-gierakowski commented
> * Note: does not support targeted catch blocks used in [pub-api request](https://github.com/DeversiFi/launch-deversifi/blob/dev/dvf-pub-api/src/lib/services/request.js#L14-L20), this was bluebird promise logic which is unnecessary overhead

On stark-trading we use [aigle](https://github.com/suguru03/aigle) which provides similar functionality but is better maintained than bluebird. I’m not suggesting that we use it here though as it can be used when needed by wrapping standard promise instance stop the point of use.

2021-11-08 09:02 UTC, sjpbeale commented
> > * Note: does not support targeted catch blocks used in [pub-api request](https://github.com/DeversiFi/launch-deversifi/blob/dev/dvf-pub-api/src/lib/services/request.js#L14-L20), this was bluebird promise logic which is unnecessary overhead
> 
> On stark-trading we use [aigle](https://github.com/suguru03/aigle) which provides similar functionality but is better maintained than bluebird. I’m not suggesting that we use it here though as it can be used when needed by wrapping standard promise instance stop the point of use.

Thanks @adrian-gierakowski - yep, maybe we keep the current implementation simple and can have the additional targeted catch down to the consumer if desired :+1:

2021-11-08 09:34 UTC, adrian-gierakowski requested changes
looks good, the only important comment is about `expect().reject`

2021-11-08 09:34 UTC, adrian-gierakowski commented on lib/request.test.js
> +      }).rejects.toThrow(InvalidOptionError)
`expect().rejects` returns a promise so it needs to be awaited or returned 

and it can also be passed a promise (instead of function returning a promise), so the whole thing could be slightly simplified 

```suggestion
    it('fails with InvalidOptionError using data option for get', () => {
      return expect(request.get(`${apiDomain}${getTest.url}`, {
        data: {
          test: 'test'
        }
      })).rejects.toThrow(InvalidOptionError)
    })
```

2021-11-08 09:34 UTC, adrian-gierakowski commented on lib/request.test.js
> +      }).rejects.toThrow(InvalidOptionError)
as above

2021-11-08 09:34 UTC, adrian-gierakowski commented on lib/request.test.js
> +      }).rejects.toThrow(StatusCodeError)
as above

2021-11-08 09:34 UTC, adrian-gierakowski commented on lib/request.test.js
> +      }).rejects.toThrow(RequestError)
as above

2021-11-08 09:34 UTC, adrian-gierakowski commented on lib/request.test.js
> +      }).rejects.toThrow(RequestError)
as above

2021-11-08 09:42 UTC, gvko requested changes
Nice one! I was waiting for when we will switch away from `request-promise` and use some properly maintained lib like `axios`. 
Also, I support and appreciate the more OO style of coding! :) 

Just left a few comments about better code structure.

2021-11-08 09:42 UTC, gvko commented on lib/index.js
> +  requestErrors: require('./request.errors')
We have a bunch of different file naming standards throughout the project, which is quite bad, but I believe we should slowly point towards one and follow it.
The dot-notation is not smth we normally use. Is there a particular reason you named it this way?
I would suggest we go for `train-case`, since dashes are the most safe character, across any system.

2021-11-08 09:42 UTC, gvko commented on lib/request.errors.js
> +// InvalidOptionError
I think it'd be better if you put JSDoc comments to describe the classes instead of inline comments.
Inline comments would be more suitable for commenting certain business logic of "why it happens this way".

2021-11-08 09:42 UTC, gvko commented on lib/request.js
> +const rq = require('axios')
Naming variables in such short way is an anti-pattern. We are not saving anything by this. It only makes the code less readable.
I'd suggest either name it `request` or just `axios`.

2021-11-08 09:49 UTC, arijoon commented on lib/request.js
> +class Request {
Do these need to be defined within a `class` or can they just be exported functions?

2021-11-08 09:49 UTC, arijoon commented on lib/request.js
> +  const { message, status, config: { url } } = error.toJSON?.() ?? {
nice, more C# functionalities should be ported to js

2021-11-08 10:14 UTC, arijoon commented
> Also, I support and appreciate the more OO style of coding! :)

could be useful to have a team discussion regarding this, as I advised Piotr to avoid OO when it comes to Market-data v2 since we would encounter a divergence in our codebase (realistically we will never rewrite the large services to change) of OO and functional and same logic could end up looking very different
Would be keen to get everyone's input on this as well @adrian-gierakowski @gvko @Neozaru @sjpbeale of what would be ideal way to proceed but ensure we maintain consistency

2021-11-08 10:36 UTC, adrian-gierakowski commented on lib/request.js
> +  const { message, status, config: { url } } = error.toJSON?.() ?? {
I see it more as JS finally caching up with CoffeeScript ;)

2021-11-08 10:57 UTC, gvko commented
> > Also, I support and appreciate the more OO style of coding! :)
> 
> could be useful to have a team discussion regarding this, as I advised Piotr to avoid OO when it comes to Market-data v2 since we would encounter a divergence in our codebase (realistically we will never rewrite the large services to change) of OO and functional and same logic could end up looking very different Would be keen to get everyone's input on this as well @adrian-gierakowski @gvko @Neozaru @sjpbeale of what would be ideal way to proceed but ensure we maintain consistency

Yeah, you have a good point. 👍 

But regarding this:
> realistically we will never rewrite the large services to change
It will happen, _if_ we eventually switch to TypeScript.

2021-11-08 11:06 UTC, adrian-gierakowski commented
> > Also, I support and appreciate the more OO style of coding! :)
> 
> could be useful to have a team discussion regarding this, as I advised Piotr to avoid OO when it comes to Market-data v2 since we would encounter a divergence in our codebase (realistically we will never rewrite the large services to change) of OO and functional and same logic could end up looking very different Would be keen to get everyone's input on this as well @adrian-gierakowski @gvko @Neozaru @sjpbeale of what would be ideal way to proceed but ensure we maintain consistency

Personally I rarely find a good reason for using OO features in JS while writing backend code. I think the only classes I have written in over 5 years were subclasses of `Error`. I'm not against using Classes in principle, as long as it doesn't lead to using unnecessary mutable state. One other thing which is annoying about class instance methods which access `this` is that you need to bind them to pass them into higher order functions (like `Array.forEech\map`), for example, the following would not turn out well if `postOrder` implementation was  accessing `this`:

```js
orderRequestDataArray.map(apiClientClassInstance.postOrder)
```

it would have to be rewritten in one of the following ways to make it work:


```js
orderRequestDataArray.map(data => apiClientClassInstance.postOrder(data))
```


```js
orderRequestDataArray.map(apiClientClassInstance.postOrder.bind(apiClientClassInstance))
```

2021-11-08 11:08 UTC, adrian-gierakowski commented
> > realistically we will never rewrite the large services to change
> 
> It will happen, _if_ we eventually switch to TypeScript.

Why would moving to `TypeScript` necessitate a full rewrite? And btw. TS is awesome  for `FP` :)

2021-11-08 14:49 UTC, sjpbeale commented on lib/request.js
> +const rq = require('axios')
This was because the response has a key "request" which I'm destructuring to remove in sendRequest below, I'll have a think if there's something better... I'd prefer not to use the library name so it doesn't get left behind in case of changing the lib at a later date.

2021-11-08 15:23 UTC, sjpbeale commented on lib/request.test.js
> +      }).rejects.toThrow(RequestError)
Left this one in to handle the thrown error and re enable net connect.

2021-11-08 15:33 UTC, sjpbeale commented
> > Also, I support and appreciate the more OO style of coding! :)
> 
> could be useful to have a team discussion regarding this, as I advised Piotr to avoid OO when it comes to Market-data v2 since we would encounter a divergence in our codebase (realistically we will never rewrite the large services to change) of OO and functional and same logic could end up looking very different Would be keen to get everyone's input on this as well @adrian-gierakowski @gvko @Neozaru @sjpbeale of what would be ideal way to proceed but ensure we maintain consistency

For me it's more recent habit, as node started supporting es modules as well as commonjs, I started using it so that there was consistency with moving between frontend scripts built with webpack and backend node - I have a feeling there is some benefit to es modules when it comes to loading, commonjs downloads and runs packages synchronously, es modules downloads asynchronously and runs synchronously.  To make this switch for current code base would be a big change though.

2021-11-08 15:44 UTC, adrian-gierakowski commented
> > > Also, I support and appreciate the more OO style of coding! :)
> > 
> > 
> > could be useful to have a team discussion regarding this, as I advised Piotr to avoid OO when it comes to Market-data v2 since we would encounter a divergence in our codebase (realistically we will never rewrite the large services to change) of OO and functional and same logic could end up looking very different Would be keen to get everyone's input on this as well @adrian-gierakowski @gvko @Neozaru @sjpbeale of what would be ideal way to proceed but ensure we maintain consistency
> 
> For me it's more recent habit, as node started supporting es modules as well as commonjs, I started using it so that there was consistency with moving between frontend scripts built with webpack and backend node - I have a feeling there is some benefit to es modules when it comes to loading, commonjs downloads and runs packages synchronously, es modules downloads asynchronously and runs synchronously. To make this switch for current code base would be a big change though.

@sjpbeale I'm not 100% sure I understand how your comment about use of commonjs vs es modules relates to the discussion?

2021-11-08 15:48 UTC, arijoon commented on lib/request.test.js
> +      }).rejects.toThrow(RequestError)
the `expect` result still needs to be either `await`ed or returned, otherwise this test could finish and your promise result still pending

2021-11-08 15:49 UTC, arijoon approved these changes
Looks good aside from not awaiting `async` expect assertions, feel free to merge after fixing that. there is a jest flag that will show you open handles, you can use that to verify that could cause an open handle

2021-11-08 15:58 UTC, adrian-gierakowski approved these changes
just few couple of minor comments

2021-11-08 15:58 UTC, adrian-gierakowski commented on lib/request.test.js
> +      }).rejects.toThrow(RequestError)
that's cool, but we still need: `return expect(async () => {`

2021-11-08 16:30 UTC, sjpbeale commented on lib/request.test.js
> +      }).rejects.toThrow(RequestError)
hmm... having issues with nock disallowed net connect error popping up with expect using return or await... checking why...

2021-11-09 08:30 UTC, gvko approved these changes

2021-11-09 08:50 UTC, gvko commented
> > > Also, I support and appreciate the more OO style of coding! :)
> > 
> > 
> > could be useful to have a team discussion regarding this, as I advised Piotr to avoid OO when it comes to Market-data v2 since we would encounter a divergence in our codebase (realistically we will never rewrite the large services to change) of OO and functional and same logic could end up looking very different Would be keen to get everyone's input on this as well @adrian-gierakowski @gvko @Neozaru @sjpbeale of what would be ideal way to proceed but ensure we maintain consistency
> 
> Personally I rarely find a good reason for using OO features in JS while writing backend code. I think the only classes I have written in over 5 years were subclasses of `Error`. I'm not against using Classes in principle, as long as it doesn't lead to using unnecessary mutable state. One other thing which is annoying about class instance methods which access `this` is that you need to bind them to pass them into higher order functions (like `Array.forEech\map`), for example, the following would not turn out well if `postOrder` implementation was accessing `this`:
> 
> ```js
> orderRequestDataArray.map(apiClientClassInstance.postOrder)
> ```
> 
> it would have to be rewritten in one of the following ways to make it work:
> 
> ```js
> orderRequestDataArray.map(data => apiClientClassInstance.postOrder(data))
> ```
> 
> ```js
> orderRequestDataArray.map(apiClientClassInstance.postOrder.bind(apiClientClassInstance))
> ```

Writing functional code (in JS at least) doesn't safeguard you from mutable state. Just take a look at the MarketData service. The core of the service is based on that. And it's all written in functional syntax. So, it depends on what the programmer(s) do.
The benefit I see from OO is that it forces you to structure your code in a more understandable way and to some degree also forces you to think about how you structure the overall architecture of a given service. The architecture of StarkTrading is simply bad. I don't even wanna mention MarketData... I strongly believe having used more OO would've indirectly forced the devs to group and structure the logical parts of the services in a better way - smaller chunks of domains that take care of separation of concern.

Also, I see nothing wrong with this code:
```
orderRequestDataArray.map(data => apiClientClassInstance.postOrder(data))
```
compared to:
```
orderRequestDataArray.map(apiClientClassInstance.postOrder)
```
Saving a few chars doesn't improve the code. Some might call this "boilerplate code", I call it "self-explanatory code". Our codebase is littered with examples of functions nested on multiple levels. And we're paying the price of this now, by having to deal with code hard to read. Luckily, we're slowly changing that...

As the quote says: _Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live._

2021-11-09 08:50 UTC, sjpbeale commented on lib/request.test.js
> +      }).rejects.toThrow(RequestError)
Issue above was due to jest test environment being jsdom instead of node, it intercepts http requests and logs a network error for that specific test.  Updated the test but skipped it for now to avoid console error, we can enable it if we move to jest test env node.

2021-11-09 08:52 UTC, sjpbeale commented on lib/request.js
> +}
required errors at the top and destructured separately so that errors can be exported at the bottom without needing to manually type error names

2021-11-09 10:46 UTC, adrian-gierakowski commented on lib/request.test.js
> +    })
it looks like it only logs an error, but doesn't fail

I think we should run tests with both node and jsdom env since this code is intended to be used both in node and in the browser, I created a PR: https://github.com/DeversiFi/dvf-utils/pull/42, which will merge into this branch. Please merge it if you're happy with it and then go ahead and merge this PR into master.

2021-11-10 07:46 UTC, sjpbeale commented on lib/request.test.js
> +    })
:+1:

2021-11-10 07:49 UTC, merged